definitions:
  core.GPS:
    properties:
      created_at:
        type: string
      device_id:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      timestamp:
        type: string
      updated_at:
        type: string
    required:
    - device_id
    - latitude
    - longitude
    - timestamp
    type: object
  core.Gyroscope:
    properties:
      created_at:
        type: string
      device_id:
        type: string
      id:
        type: integer
      timestamp:
        type: string
      updated_at:
        type: string
      x:
        type: number
      "y":
        type: number
      z:
        type: number
    required:
    - device_id
    - timestamp
    - x
    - "y"
    - z
    type: object
  core.Photo:
    properties:
      created_at:
        type: string
      device_id:
        type: string
      id:
        type: integer
      photo:
        type: string
      recognized:
        type: boolean
      similarity:
        type: number
      timestamp:
        type: string
      updated_at:
        type: string
    required:
    - device_id
    - photo
    - timestamp
    type: object
info:
  contact: {}
paths:
  /telemetry/gps:
    post:
      consumes:
      - application/json
      description: Recebe e salva dados de GPS de dispositivos
      parameters:
      - description: Dados de GPS
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/core.GPS'
      produces:
      - application/json
      responses:
        "201":
          description: Mensagem de sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erro de validação
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Receber dados de GPS
      tags:
      - telemetria
  /telemetry/gyroscope:
    post:
      consumes:
      - application/json
      description: Recebe e salva dados do giroscópio de dispositivos
      parameters:
      - description: Dados do giroscópio
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/core.Gyroscope'
      produces:
      - application/json
      responses:
        "201":
          description: Mensagem de sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erro de validação
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Receber dados do giroscópio
      tags:
      - telemetria
  /telemetry/photo:
    post:
      consumes:
      - application/json
      description: Recebe e salva dados de foto de dispositivos
      parameters:
      - description: Dados da foto
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/core.Photo'
      produces:
      - application/json
      responses:
        "201":
          description: Mensagem de sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erro de validação
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Erro interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Receber dados de foto
      tags:
      - telemetria
swagger: "2.0"
